FROM node:12

ADD package-lock.json package.json ./
RUN npm install
ADD .babelrc webpack.config.js ./
ADD public ./public
ADD server ./server
ADD src ./src
RUN npm run build

ENV DB_USER docker
ENV DB_PASSWORD docker
ENV DB_NAME api
ENV DB_HOST postgres
ENV DB_PORT 5432

ENV PATH="./node_modules/ffmpeg-static/bin/linux/x64:${PATH}"

EXPOSE 7000

ENTRYPOINT node server/server.js