version: '3'
networks:
  internal:
    driver: bridge

services:
  pg:
    build:
      context: .
      dockerfile: Dockerfile.pg
    image: pg
    ports:
      - "5433:5432"
    networks:
      internal:
        aliases:
          - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: web
    ports:
      - "3000:3000"
      - "7000:7000"
    networks:
      - internal
